// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyNrkbdVo7PfUFmViT0sbys0Juap9Rvjw',
    appId: '1:74965765734:web:4a5a60a5707587a53fa7a7',
    messagingSenderId: '74965765734',
    projectId: 'savebox2021',
    authDomain: 'savebox2021.firebaseapp.com',
    databaseURL: 'https://savebox2021-default-rtdb.firebaseio.com',
    storageBucket: 'savebox2021.appspot.com',
    measurementId: 'G-172E4Z8LQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OANoqjhj5j8YAFHhZnEy7nH3xHBLr0w',
    appId: '1:74965765734:android:c5096afd83b0a7f73fa7a7',
    messagingSenderId: '74965765734',
    projectId: 'savebox2021',
    databaseURL: 'https://savebox2021-default-rtdb.firebaseio.com',
    storageBucket: 'savebox2021.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_nKEBBoyNn60ZVOj9iQajk_dyP8HktQ',
    appId: '1:74965765734:ios:bc74c224fc73f7ad3fa7a7',
    messagingSenderId: '74965765734',
    projectId: 'savebox2021',
    databaseURL: 'https://savebox2021-default-rtdb.firebaseio.com',
    storageBucket: 'savebox2021.appspot.com',
    iosClientId: '74965765734-526c42us5kia1vldkthioenk5vqgcv98.apps.googleusercontent.com',
    iosBundleId: 'com.example.savebox',
  );
}
